server:
  port: 8081
spring:
  application:
    name: User
  http:
    multipart:
      max-file-size: 40MB
      max-request-size: 40MB
springfox:
  documentation:
     swagger:
        v2:
          path: /handsdevice-0.0.1-SNAPSHOT/api-docs